[id="proc-creating-api-draft"]
= Creating an API draft

[role="_abstract"]
Use the {studio-long} web console to create an OpenAPI or AsyncAPI definition.

.Prerequisites
* You're logged in to the {studio} web console.

.Procedure
. In the {studio} web console, click *Create draft*.
. Complete the form to provide the following details for the new draft:
* *Name*: Enter a unique draft name, such as `My API`.
* *Description* _(Optional)_: Enter a short description of the draft.
* *Type*: Accept the default value *OpenAPI*, or select another API type from the list.
* *Version* _(OpenAPI only)_: Accept the default value *3.0.2*, or select another version from the list.
* *Template*: Select the *Pet Store Example* template, or select another template from the list.
. Click *Create*. The new API draft opens in the draft editor.
. Select the draft title and click the pen icon. Change the draft title to *Orders* and click the *Save changes* icon.
+
NOTE: Editing the draft _title_ does not change the draft _name_. To rename a draft, click *Actions > Edit draft metadata*, edit the draft name, and click *Save*.
+
. Click the *Design* tab, and optionally edit the draft as follows:
* Provide a version number and a description.
* _(AsyncAPI only)_ Define terms of service.
* Add your contact information: name, email address, and URL.
* Select a license.
* _(OpenAPI only)_ Define tags.
* Define one or more servers.
* Configure a security scheme.
* _(OpenAPI only)_ Specify security requirements.
* _(OpenAPI only)_ Configure vendor extensions.
. Click the *Source* tab, and review the live preview of the draft.
The content of the *Source* tab automatically updates when you edit values on the editor page.
. _(Optional)_ To see the changes that you made since the last save, click *Actions > Show draft changes*.
. _(Optional)_ In the left pane of the draft editor, you can add the following items:
* _(OpenAPI only)_ Resource paths, data types, and responses
* _(AsyncAPI only)_ Channels, data types, messages, operation traits, and message traits
. Click *Save*.
+
The new draft is listed on the *API and Schema Designs* page.
You can use the options icon (three vertical dots) to view or edit the draft details, edit the draft content, export the draft to {registry-long}, download the draft to a file, or delete the draft.
